##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.9.0-B19] date: [Mon Mar 23 16:57:10 PDT 2026] 
# FIXED: LVGL sources link reliably (no double-prefix paths; no object collisions)
##########################################################################################################################

######################################
# target
######################################
TARGET = Senior_Design

######################################
# building variables
######################################
DEBUG = 1
OPT = -Og

#######################################
# Build path
#######################################
BUILD_DIR = build

##########################################################
# LVGL
##########################################################
LVGL_PATH := Drivers/lvgl
include $(LVGL_PATH)/lvgl.mk

######################################
# source
######################################
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32h7xx_it.c \
Core/Src/stm32h7xx_hal_msp.c \
Drivers/BSP/STM32H7xx_Nucleo/stm32h7xx_nucleo.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c \
Core/Src/system_stm32h7xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Core/Src/ILI9341.c \
Core/Src/lv_port_disp.c \
Core/Src/DS18B20.c \
Core/Src/GUI.c \
Core/Src/plantProfiles.c \
Core/Src/touchscreen.c \
Core/Src/TDS_Sensor_Driver.c \
Core/Src/settingsScreen.c \
Core/Src/plantSelectionScreen.c \
Core/Src/DS3231s.c \
Core/Src/fans.c \
Core/Src/homeScreen.c

ASM_SOURCES =  \
startup_stm32h753xx.s

ASMM_SOURCES =

#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
CPU = -mcpu=cortex-m7
FPU = -mfpu=fpv5-d16
FLOAT-ABI = -mfloat-abi=hard
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

AS_DEFS =

C_DEFS =  \
-DUSE_PWR_LDO_SUPPLY \
-DUSE_HAL_DRIVER \
-DSTM32H753xx

AS_INCLUDES =
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32H7xx_HAL_Driver/Inc \
-IDrivers/STM32H7xx_HAL_Driver/Inc/Legacy \
-IDrivers/BSP/STM32H7xx_Nucleo \
-IDrivers/CMSIS/Device/ST/STM32H7xx/Include \
-IDrivers/CMSIS/Include

ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections
CFLAGS  = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

# ---- LVGL include paths ----
CFLAGS  += -I$(LVGL_PATH) -I$(LVGL_PATH)/src
ASFLAGS += -I$(LVGL_PATH)

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif

# Generate dependency information
CFLAGS += -MMD -MP

#######################################
# LDFLAGS
#######################################
LDSCRIPT = STM32H753XX_FLASH.ld
LIBS = -lc -lm -lnosys
LIBDIR =
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) \
          -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections -u _printf_float

#######################################
# Add LVGL sources (bulletproof: handles src/... OR Drivers/lvgl/src/...)
#######################################
# Normalize LVGL source paths to avoid "Drivers/lvgl/Drivers/lvgl/..." double prefix.
LVGL_CSRCS := $(CSRCS)
LVGL_CSRCS := $(patsubst src/%,$(LVGL_PATH)/src/%,$(LVGL_CSRCS))
C_SOURCES  += $(LVGL_CSRCS)

# If lvgl.mk provides ASM sources, normalize those too
LVGL_ASRCS := $(ASRCS)
LVGL_ASRCS := $(patsubst src/%,$(LVGL_PATH)/src/%,$(LVGL_ASRCS))
AS_SOURCES := $(LVGL_ASRCS)

#######################################
# default action: build all
#######################################
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin

#######################################
# Objects (NO notdir — avoids collisions)
#######################################
OBJECTS  = $(patsubst %.c,$(BUILD_DIR)/%.o,$(C_SOURCES))
OBJECTS += $(patsubst %.s,$(BUILD_DIR)/%.o,$(ASM_SOURCES))
OBJECTS += $(patsubst %.S,$(BUILD_DIR)/%.o,$(ASMM_SOURCES))
OBJECTS += $(patsubst %.S,$(BUILD_DIR)/%.o,$(AS_SOURCES))

#######################################
# build rules
#######################################
$(BUILD_DIR)/%.o: %.c Makefile
	@mkdir -p $(dir $@)
	$(CC) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile
	@mkdir -p $(dir $@)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.S Makefile
	@mkdir -p $(dir $@)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile | $(BUILD_DIR)
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir -p $@

flash:
	st-flash write build/Senior_Design.bin 0x8000000

clean:
	-rm -fR $(BUILD_DIR)

# Dependencies (portable for nested object paths)
-include $(shell find $(BUILD_DIR) -name "*.d" 2>/dev/null)

# *** EOF ***
